title: Métodos Computacionales
description: Instituto de Física, UdeA, 2025
theme: just-the-docs

url: https://just-the-docs.github.io

#logo: "docs/images/logo.png"

search_enabled: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Anuncio
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Importante
    color: red
  aviso:
    title: Atención
    color: orange